# Generated by Django 5.1.5 on 2025-01-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
