# Generated by Django 5.1.5 on 2025-01-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menuitem_menu_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
